import {View, Text, Dimensions} from 'react-native';
import React from 'react';
import SkeletonPlaceholder from 'react-native-skeleton-placeholder';
import LocalConfig from '../LocalConfig';

export default function HomeScreenLoading() {
  return (
    <SkeletonPlaceholder
      backgroundColor={LocalConfig.COLOR.BLACK}
      highlightColor={LocalConfig.COLOR.BLACK_LIGHT}>
      <SkeletonPlaceholder.Item
        width={Dimensions.get('screen').width}
        height={200}
        padding={'3%'}
        borderRadius={10}
      />
      <SkeletonPlaceholder.Item flexDirection="row" margin={10}>
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          borderRadius={100}
          borderWidth={5}
          marginLeft={'3%'}
          borderColor="white"
          marginTop={'5%'}
          position="relative"
        />
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          borderRadius={100}
          borderWidth={5}
          marginLeft={'3%'}
          borderColor="white"
          marginTop={'5%'}
          position="relative"
        />
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          borderRadius={100}
          borderWidth={5}
          marginLeft={'3%'}
          borderColor="white"
          marginTop={'5%'}
          position="relative"
        />
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          borderRadius={100}
          borderWidth={5}
          marginLeft={'3%'}
          borderColor="white"
          marginTop={'5%'}
          position="relative"
        />
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          marginLeft={'3%'}
          marginTop={'5%'}
          borderRadius={10}
          borderWidth={5}
          borderColor="white"
          position="relative"
        />
      </SkeletonPlaceholder.Item>
      <SkeletonPlaceholder.Item
        width={120}
        height={20}
        marginLeft={'3%'}
        marginTop={'4%'}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item
        width={'95%'}
        height={20}
        marginLeft={'3%'}
        marginTop={'4%'}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item flexDirection="row">
        <SkeletonPlaceholder.Item
          width={120}
          height={20}
          marginLeft={'13%'}
          marginTop={'15%'}
          borderRadius={4}
        />
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          borderRadius={10}
          borderWidth={5}
          marginLeft={'35%'}
          borderColor="white"
          marginTop={'3%'}
          position="relative"
        />
      </SkeletonPlaceholder.Item>
      <SkeletonPlaceholder.Item
        width={120}
        height={20}
        marginLeft={'6%'}
        marginTop={'-13%'}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item
        width={120}
        height={20}
        marginLeft={'6%'}
        marginTop={'-6%'}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item
        width={'95%'}
        height={20}
        marginLeft={'3%'}
        marginTop={12}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item flexDirection="row">
        <SkeletonPlaceholder.Item
          width={120}
          height={20}
          marginLeft={'13%'}
          marginTop={'15%'}
          borderRadius={4}
        />
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          borderRadius={10}
          borderWidth={5}
          marginLeft={'35%'}
          borderColor="white"
          marginTop={'3%'}
          position="relative"
        />
      </SkeletonPlaceholder.Item>
      <SkeletonPlaceholder.Item
        width={120}
        height={20}
        marginLeft={'6%'}
        marginTop={'-13%'}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item
        width={120}
        height={20}
        marginLeft={'6%'}
        marginTop={'-6%'}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item
        width={'95%'}
        height={20}
        marginLeft={'3%'}
        marginTop={12}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item flexDirection="row">
        <SkeletonPlaceholder.Item
          width={120}
          height={20}
          marginLeft={'13%'}
          marginTop={'15%'}
          borderRadius={4}
        />
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          borderRadius={10}
          borderWidth={5}
          marginLeft={'35%'}
          borderColor="white"
          marginTop={'3%'}
          position="relative"
        />
      </SkeletonPlaceholder.Item>
      <SkeletonPlaceholder.Item
        width={120}
        height={20}
        marginLeft={'6%'}
        marginTop={'-13%'}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item
        width={120}
        height={20}
        marginLeft={'6%'}
        marginTop={'-6%'}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item
        width={'90%'}
        height={20}
        marginLeft={'3%'}
        marginTop={12}
        borderRadius={4}
      />
      <SkeletonPlaceholder.Item flexDirection="row">
        <SkeletonPlaceholder.Item
          width={120}
          height={20}
          marginLeft={'13%'}
          marginTop={'15%'}
          borderRadius={4}
        />
        <SkeletonPlaceholder.Item
          width={100}
          height={100}
          borderRadius={10}
          borderWidth={5}
          marginLeft={'35%'}
          borderColor="white"
          marginTop={'3%'}
          position="relative"
        />
      </SkeletonPlaceholder.Item>
      <SkeletonPlaceholder.Item
        width={120}
        height={20}
        marginLeft={'6%'}
        marginTop={'-15%'}
        borderRadius={4}
      />
    </SkeletonPlaceholder>
  );
}
